services:
  ev-api:
    build: .
    image: ev-api:latest      # local tag
    container_name: ev-api
    ports:
      - 8080:8080
    environment:
      # optional – enables the same H2 in-mem DB
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
